### ISSUE TITLE
Language selection/switchover for bilingual songs

### ISSUE THREAD

**Issue by perfektionix** [Boddlnagg/WordsLive#12]
Currently it is possible to switch the two languages for bilingual songs, but it is impossible to display only the first or second language. In this case it would be desirable to display only one language. Therefore it would be useful to have four icons in the toolbar for quick selection of the display:

"1/2" for the original bilingual display
"2/1" for the inverted, bilingual display
"-1-" for exclusive display of original language (first language)
"-2-" for the exclusive display of the translation (second language)

And it would be good, of course, if the selected setting is saved in the portfolio and is retained after switching to another song.

**Comment by Boddlnagg** [comment]
> And it would be good, of course, if the selected setting is saved in the portfolio and is retained after switching to another song.

To clarify: If that setting is saved in the portfolio, it would mean that the following would happen:
- Song 1 is first language EN, second language DE
- Song 2 is first language DE, second language EN

When I now select "2/1" for inverted display for the first song because I want it in DE I would then get the second one in EN, but that's probably not what is expected ... or am I missing something?

**Comment by Boddlnagg** [comment]
I think it should be stored per song, per portfolio. In the same way we could also store a separate "song variant" setting to have multiple variants for the song part order.

**Comment by perfektionix** [comment]
I agree. Currently, the selection is already made song specific. Only it is not saved, so after a portfolio load it is back to the variant stored in the editor. So: still song specific, but saved in the portfolio.
The second item I don't quite understand. Do you mean here a setting in the editor, according to which I can create different arrangements of the elements of a song? And how should these be named or selected?

**Comment by Boddlnagg** [comment]
> The second item I don't quite understand. Do you mean here a setting in the editor, according to which I can create different arrangements of the elements of a song?

Yes

> And how should these be named or selected?

That is still something I have to think about 😉
